### PR TITLE
Feature/accordion - Add accordion component

### PR DESCRIPTION
**Pull request by abh1nash**
Base component prepared. Needs to be tested for accessibility.

- Can be toggled
- Has aria- attributes
- Can add custom classes to active or inactive state of the components

### CODE REVIEW

**Comment by aashishkhatiwada** [comment]
working.

**Comment by abh1nash** [comment]
Great, could you approve this one please (if its good with accessibility @aashishkhatiwada)?

**Comment by aashishkhatiwada** [comment]
I am searching for the way for approving the review, but couldn't find it. Where is that option  on github?

**Review by aashishkhatiwada — APPROVED** [review]
Merged.

**Pull request merged**
